[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rust_program_anchor = "F7uwK9BXr7orrQWJujdoTVbd7P7yMDnPA84udYYyPPLM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/gaopenghao/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
